homepage = "https://github.com/cli/cli"
architectures = ["amd64", "arm64"]
source = "github"
update_policy = "track"

[sources.github]
repo = "cli/cli"

[sources.github.asset_patterns]
amd64 = "gh_*_linux_amd64.deb"
arm64 = "gh_*_linux_arm64.deb"
