homepage = "https://github.com/agalwood/Motrix"
architectures = ["amd64", "arm64"]
source = "github"
update_policy = "track"

[sources.github]
repo = "agalwood/Motrix"

[sources.github.asset_patterns]
amd64 = "Motrix_*_amd64.deb"
arm64 = "Motrix_*_arm64.deb"
